#---------------------------------------------------------------*
#                                                               *
#                        MAKEFILE                               *
#    for building on Win32 Sara command line tools for Win32    *
#                                                               *
#---------------------------------------------------------------*

#--- Release and debug versions of galgas
EXECUTABLE := sara.exe
EXECUTABLE_DEBUG := sara_debug.exe

#---------------------------------------------------------------*

#--- Linker Options for this platform
PLATFORM_LINKER_OPTIONS := -lcomdlg32

#---------------------------------------------------------------*

include ../common_files_for_make/makefile.mke

#---------------------------------------------------------------*
#                                                               *
#     Include MinGW gcc tools definitions for Win32             *
#                                                               *
#---------------------------------------------------------------*

include $(LIB_PM_PATH)/included_makefiles/msys_on_win32.mke

#---------------------------------------------------------------*
#                                                               *
#     Include makefile that performs actual work                *
#                                                               *
#---------------------------------------------------------------*

include $(LIB_PM_PATH)/included_makefiles/generic_makefile.mke

#---------------------------------------------------------------*
