//---------------------------------------------------------------------------*
//                                                                           *
//                        File 'grammar_sara_main.h'                         *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     january 4th, 2006, at 21h44'17"                       *
//                                                                           *
// This file is free software; you can redistribute it and/or modify it      *
// under the terms of the GNU Lesser General Public License as published     *
// by the Free Software Foundation; either version 2 of the License, or      *
// (at your option) any later version.                                       *
//                                                                           *
// This file is distributed in the hope it will be useful, but WITHOUT       *
// ANY WARRANTY; without even the implied warranty of MERCHANDIBILITY or     *
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public       *
// License for more details.                                                 *
//                                                                           *
// You should have received a copy of the GNU General Public License along   *
// with this program; if not, write to the Free Software Foundation          *
// Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA            *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

class sara_main : public C_defaultUserSemanticActions {
  protected : sara_scanner mScanner_ ;
  protected : C_galgas_terminal_io mTerminalIO ;
  protected : C_String mSourceFileExtension_ ;

//--- Command line options
  protected : bool mOption_sara_cli_options_displayBDDvaluesCount ;
  protected : bool mOption_sara_cli_options_displayBDDvalues ;

//--- Constructor
  public : sara_main (const C_galgas_io_parameters & inIOparameters) ;

  public : void doCompilation (const C_String & inSourceFileName_,
                               sint16 & returnCode) ;
//--- START OF USER ZONE 2

//--- END OF USER ZONE 2

//--- Prologue and epilogue
  public : void _prologue (void) ;
  public : void _epilogue (void) ;
} ;

