//---------------------------------------------------------------------------*
//                                                                           *
//                 File 'include_C_machineCheckIdentical.h'                  *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     october 14th, 2006, at 22h48'14"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                   class 'cPtr_C_machineCheckIdentical'                    *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_machineCheckIdentical : public cPtr_AC_job {
  private : typedef cPtr_AC_job inherited ;
//--- START OF USER ZONE 2

  public : virtual void compute (C_Lexique & inLexique,
                                 TC_Array <C_saraMachine> & ioSaraSystemArray,
                                 const bool inDisplayBDDvaluesCount,
                                 const bool inDisplayBDDvalues) const ;

//--- END OF USER ZONE 2

  public : cPtr_C_machineCheckIdentical (const GGS_luint & ,
                                const GGS_luint &  COMMA_LOCATION_ARGS) ;
  public : GGS_luint  mMachineIndex1 ;
  public : GGS_luint  mMachineIndex2 ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

