//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_C_machineComponent.h'                     *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 12th, 2006, at 21h54'26"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_C_machineComponent'                       *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef C_machineComponent_DEFINED
#define C_machineComponent_DEFINED

class cPtr_C_machineComponent : public cPtr_AC_job {
  private : typedef cPtr_AC_job inherited ;
//--- START OF USER ZONE 2

  public : virtual void compute (C_Lexique & inLexique,
                                 TC_Array <C_saraMachine> & ioSaraSystemArray,
                                 const bool inDisplayBDDvaluesCount,
                                 const bool inDisplayBDDvalues) const ;

//--- END OF USER ZONE 2

  public : cPtr_C_machineComponent (const GGS_lstring & ,
                                const GGS_luint & ,
                                const GGS_uint & ,
                                const GGS_uint & ,
                                const GGS_M_variablesMap & ,
                                const GGS_AC_machineDefinition &  COMMA_LOCATION_ARGS) ;
  public : GGS_lstring  mMachineName ;
  public : GGS_luint  mMachineIndex ;
  public : GGS_uint  mInputVariableCount ;
  public : GGS_uint  mInputAndInternalVariableCount ;
  public : GGS_M_variablesMap  mVariablesMap ;
  public : GGS_AC_machineDefinition  mDefinition ;
} ;

//---------------------------------------------------------------------------*

class GGG_C_machineComponent : public GGG_AC_job {
  private : typedef GGG_AC_job inherited ;
  public : GGG_C_machineComponent (const GGS_lstring & ,
                                const GGS_luint & ,
                                const GGS_uint & ,
                                const GGS_uint & ,
                                const GGS_M_variablesMap & ,
                                const GGS_AC_machineDefinition &  COMMA_LOCATION_ARGS) ;
} ;

//---------------------------------------------------------------------------*

#endif

