//---------------------------------------------------------------------------*
//                                                                           *
//                     File 'include_C_andExpression.h'                      *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                       june 6th, 2006, at 22h41'39"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                       class 'cPtr_C_andExpression'                        *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_andExpression : public cPtr_AC_boolExpression {
  private : typedef cPtr_AC_boolExpression inherited ;
//--- START OF USER ZONE 2

  public : virtual C_BDD computeBDD (C_Lexique & inLexique,
                                     const TC_Array <C_saraMachine> & inSaraSystemArray,
                                     const uint16 inVariablesCount,
                                     const uint16 inBDDslotOffset) const ;

//--- END OF USER ZONE 2

  public : cPtr_C_andExpression (const GGS_AC_boolExpression & ,
                                const GGS_AC_boolExpression &  COMMA_LOCATION_ARGS) ;
  public : GGS_AC_boolExpression  mLeftExpression ;
  public : GGS_AC_boolExpression  mRightExpression ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique, C_String & ioString COMMA_LOCATION_ARGS) const ;
} ;

//---------------------------------------------------------------------------*

