//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_C_importBoolMachine.h'                    *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 20th, 2006, at 11h43'10"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_C_importBoolMachine'                      *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef C_importBoolMachine_DEFINED
#define C_importBoolMachine_DEFINED

class cPtr_C_importBoolMachine : public cPtr_AC_boolExpression {
  private : typedef cPtr_AC_boolExpression inherited ;
//--- START OF USER ZONE 2

  public : virtual C_BDD computeBDD (C_Lexique & inLexique,
                                     const TC_Array <C_saraMachine> & inSaraSystemArray,
                                     const uint16 inVariablesCount,
                                     const uint16 inBDDslotOffset) const ;

//--- END OF USER ZONE 2

  public : cPtr_C_importBoolMachine (const GGS_uint & ,
                                const GGS_location & ,
                                const GGS_L_translationVector &  COMMA_LOCATION_ARGS) ;
  public : GGS_uint  mIndexOfImportedMachine ;
  public : GGS_location  mErrorLocation ;
  public : GGS_L_translationVector  mTranslationVector ;
  public : virtual void appendForDescription (C_String & ioString) const ;
} ;

//---------------------------------------------------------------------------*

#endif

