//---------------------------------------------------------------------------*
//                                                                           *
//                   File 'include_typeDisplayBDDstats.h'                    *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 4th, 2006, at 17h43'20"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                     class 'cPtr_typeDisplayBDDstats'                      *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeDisplayBDDstats_DEFINED
#define typeDisplayBDDstats_DEFINED

class cPtr_typeDisplayBDDstats : public cPtr_AC_job {
  private : typedef cPtr_AC_job inherited ;
//--- START OF USER ZONE 2

  public : virtual void compute (C_Lexique & inLexique,
                                 TC_Array <C_saraMachine> & ioSaraSystemArray,
                                 const bool inDisplayBDDvaluesCount,
                                 const bool inDisplayBDDvalues) const ;

//--- END OF USER ZONE 2

  public : cPtr_typeDisplayBDDstats (LOCATION_ARGS) ;
} ;

//---------------------------------------------------------------------------*

#endif

