//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'include_AC_job.h'                           *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 20th, 2006, at 11h43'10"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                       abstract class 'cPtr_AC_job'                        *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef AC_job_DEFINED
#define AC_job_DEFINED

//---------------------------------------------------------------------------*

class cPtr_AC_job : public C_GGS_Object {
//--- START OF USER ZONE 2

  public : virtual void compute (C_Lexique & inLexique,
                                 TC_Array <C_saraMachine> & ioSaraSystemArray,
                                 const bool inDisplayBDDvaluesCount,
                                 const bool inDisplayBDDvalues) const = 0 ;

//--- END OF USER ZONE 2

  public : cPtr_AC_job (LOCATION_ARGS) ;
  public : virtual void appendForDescription (C_String & ioString) const = 0 ;
} ;

//---------------------------------------------------------------------------*

#endif

