//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'include_C_trans.h'                          *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                      march 20th, 2006, at 11h43'10"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                           class 'cPtr_C_trans'                            *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef C_trans_DEFINED
#define C_trans_DEFINED

class cPtr_C_trans : public cPtr_AC_machineDefinition {
  private : typedef cPtr_AC_machineDefinition inherited ;
//--- START OF USER ZONE 2

  public : virtual void computeFromExpression (C_Lexique & inLexique,
                                               const TC_Array <C_saraMachine> & inSaraSystemArray,
                                               const uint16 inVariablesCount,
                                               C_BDD & outInitialStatesBDD,
                                               C_BDD & outTerminalStatesBDD,
                                               C_BDD & outAccessibilityRelationBDD) const ;

//--- END OF USER ZONE 2

  public : cPtr_C_trans (const GGS_AC_boolExpression & ,
                                const GGS_AC_boolExpression &  COMMA_LOCATION_ARGS) ;
  public : GGS_AC_boolExpression  mSourceStateExpression ;
  public : GGS_AC_boolExpression  mTargetStateExpression ;
  public : virtual void appendForDescription (C_String & ioString) const ;
} ;

//---------------------------------------------------------------------------*

#endif

