//---------------------------------------------------------------------------*
//                                                                           *
//                File 'include_C_strongModalComposition.h'                  *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     november 2nd, 2006, at 20h14'17"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  class 'cPtr_C_strongModalComposition'                    *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_strongModalComposition : public cPtr_AC_machineDefinition {
  private : typedef cPtr_AC_machineDefinition inherited ;
//--- START OF USER ZONE 2

  public : virtual void computeFromExpression (C_Lexique & inLexique,
                                               const TC_Array <C_saraMachine> & inSaraSystemArray,
                                               const uint16 inVariablesCount,
                                               C_BDD & outInitialStatesBDD,
                                               C_BDD & outTerminalStatesBDD,
                                               C_BDD & outAccessibilityRelationBDD) const ;

//--- END OF USER ZONE 2

  public : cPtr_C_strongModalComposition (const GGS_AC_machineDefinition & ,
                                const GGS_location & ,
                                const GGS_AC_machineDefinition &  COMMA_LOCATION_ARGS) ;
  public : GGS_AC_machineDefinition  mLeftOperand ;
  public : GGS_location  mErrorLocation ;
  public : GGS_AC_machineDefinition  mRightOperand ;
//--- Method for 'description' reader
  public : virtual void appendForDescription (C_Lexique & _inLexique,
                                              C_String & ioString,
                                              const sint32 inIndentation
                                              COMMA_LOCATION_ARGS) const ;
//--- Comparison
  public : virtual bool isEqualToObject (const C_GGS_Object * inOperand) const ;
} ;

//---------------------------------------------------------------------------*

