//---------------------------------------------------------------------------*
//                                                                           *
//                      File 'include_typeResizeMap.h'                       *
//                Generated by version 1.0.0 (LL(1) grammar)                 *
//                     october 29th, 2005, at 20h16'28"                      *
//                                                                           *
// This program is free software; you can redistribute it and/or modify it   *
// under the terms of the GNU General Public License as published by the     *
// Free Software Foundation.                                                 *
//                                                                           *
// This program is distributed in the hope it will be useful, but WITHOUT    *
// ANY WARRANTY; without even the implied warranty of MERCHANDIBILITY or     *
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for  *
// more details.                                                             *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                        class 'cPtr_typeResizeMap'                         *
//                                                                           *
//---------------------------------------------------------------------------*

#ifndef typeResizeMap_DEFINED
#define typeResizeMap_DEFINED

class cPtr_typeResizeMap : public cPtr_AC_job {
  private : typedef cPtr_AC_job inherited ;
//--- START OF USER ZONE 2

  public : virtual void compute (C_Lexique & inLexique,
                                 TC_Array <C_saraMachine> & ioSaraSystemArray,
                                 const bool inDisplayBDDvaluesCount,
                                 const bool inDisplayBDDvalues) const ;

//--- END OF USER ZONE 2

  public : cPtr_typeResizeMap (const GGS_luint & ) ;
  public : GGS_luint  mNewSize ;
} ;

//---------------------------------------------------------------------------*

#endif

