//---------------------------------------------------------------------------*
//                                                                           *
//                           File 'sara_parser.h'                            *
//               Generated by version 0.14.1 (LL(1) grammar)                 *
//                     february 2nd, 2005, at 16h31'20"                      *
//                                                                           *
// This program is free software; you can redistribute it and/or modify it   *
// under the terms of the GNU General Public License as published by the     *
// Free Software Foundation.                                                 *
//                                                                           *
// This program is distributed in the hope it will be useful, but WITHOUT    *
// ANY WARRANTY; without even the implied warranty of MERCHANDIBILITY or     *
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for  *
// more details.                                                             *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef sara_parser_DEFINED
#define sara_parser_DEFINED

#include <string.h>

// Include predefined semantics types definition *
#include "memory/C_reference_count.h"
#include "galgas/AC_galgas_io.h"
#include "galgas/GGS_location.h"
#include "galgas/GGS_lbool.h"
#include "galgas/GGS_lchar.h"
#include "galgas/GGS_lstring.h"
#include "galgas/GGS_ldfloat.h"
#include "galgas/GGS_luint.h"
#include "galgas/GGS_lsint.h"
#include "galgas/AC_galgas_map.h"
// Include scanner definition *
#include "sara_scanner.h"
// Include imported semantics *
#include "sara_semantics.h"


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

void performComputations (C_lexique &,
                                GGS_M_componentMap  &) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                   Parser class sara_parser declaration                    *
//                                                                           *
//---------------------------------------------------------------------------*

class sara_parser {
  public : virtual ~sara_parser (void) {}

  protected : virtual void nt_start_symbol_ (sara_scanner &) = 0 ;

  protected : virtual void nt_component_ (sara_scanner &,
                                GGS_M_componentMap  &) = 0 ;

  protected : virtual void nt_input_expression_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) = 0 ;

  protected : virtual void nt_input_and_expression_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) = 0 ;

  protected : virtual void nt_input_primary_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) = 0 ;

  protected : void pr_start_symbol_sara_parser_203_20_ (sara_scanner &) ;

  protected : virtual sint16 select_repeat_sara_parser_0 (sara_scanner &) = 0 ;

  protected : void pr_component_sara_parser_215_17_ (sara_scanner &,
                                GGS_M_componentMap  &) ;

  protected : virtual sint16 select_repeat_sara_parser_1 (sara_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_sara_parser_2 (sara_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_sara_parser_3 (sara_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_sara_parser_4 (sara_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_sara_parser_5 (sara_scanner &) = 0 ;

  protected : virtual sint16 select_repeat_sara_parser_6 (sara_scanner &) = 0 ;

  protected : void pr_input_expression_sara_parser_326_24_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) ;

  protected : virtual sint16 select_repeat_sara_parser_7 (sara_scanner &) = 0 ;

  protected : void pr_input_and_expression_sara_parser_342_28_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) ;

  protected : virtual sint16 select_repeat_sara_parser_8 (sara_scanner &) = 0 ;

  protected : void pr_input_primary_sara_parser_358_21_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) ;

  protected : void pr_input_primary_sara_parser_369_21_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) ;

  protected : void pr_input_primary_sara_parser_382_21_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) ;

  protected : void pr_input_primary_sara_parser_394_21_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) ;

  protected : void pr_input_primary_sara_parser_404_21_ (sara_scanner &,
                                GGS_M_inputOutputVarMap  &,
                                GGS_AC_expression  &) ;

} ;

//---------------------------------------------------------------------------*

#endif
