//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'sara_grammar.cpp'                           *
//               Generated by version 0.14.1 (LL(1) grammar)                 *
//                      march 10th, 2005, at 17h29'24"                       *
//                                                                           *
// This program is free software; you can redistribute it and/or modify it   *
// under the terms of the GNU General Public License as published by the     *
// Free Software Foundation.                                                 *
//                                                                           *
// This program is distributed in the hope it will be useful, but WITHOUT    *
// ANY WARRANTY; without even the implied warranty of MERCHANDIBILITY or     *
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for  *
// more details.                                                             *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "sara_grammar.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//              L L ( 1 )    P R O D U C T I O N    R U L E S                *
//                                                                           *
//---------------------------------------------------------------------------*

#define TERMINAL(t)     ((t)+1)
#define NONTERMINAL(nt) ((-nt)-1)
#define END_PRODUCTION  (0)

static const sint16 gProductions [] = {
// At index 0 : <start_symbol>, in file 'sara_parser', line 449
  NONTERMINAL (5) // <component>
, NONTERMINAL (9) // <select_repeat_sara_parser_0>
, END_PRODUCTION
// At index 3 : <explicit_automaton>, in file 'sara_parser', line 1076
, TERMINAL (sara_scanner::sara_scanner_1_auto) // $auto$
, TERMINAL (sara_scanner::sara_scanner_1__7B) // ${$
, TERMINAL (sara_scanner::sara_scanner_1_state) // $state$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (33) // <select_repeat_sara_parser_24>
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, TERMINAL (sara_scanner::sara_scanner_1_first) // $first$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (34) // <select_repeat_sara_parser_25>
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, NONTERMINAL (35) // <select_sara_parser_26>
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, TERMINAL (sara_scanner::sara_scanner_1__3A) // $:$
, NONTERMINAL (6) // <io_expression>
, TERMINAL (sara_scanner::sara_scanner_1__7B) // ${$
, NONTERMINAL (38) // <select_repeat_sara_parser_29>
, TERMINAL (sara_scanner::sara_scanner_1__7D) // $}$
, NONTERMINAL (37) // <select_repeat_sara_parser_28>
, TERMINAL (sara_scanner::sara_scanner_1__7D) // $}$
, END_PRODUCTION
// At index 23 : <definition_expression>, in file 'sara_parser', line 845
, NONTERMINAL (3) // <definition_expression_term>
, NONTERMINAL (23) // <select_repeat_sara_parser_14>
, END_PRODUCTION
// At index 26 : <definition_expression_term>, in file 'sara_parser', line 881
, NONTERMINAL (4) // <definition_expression_factor>
, NONTERMINAL (24) // <select_repeat_sara_parser_15>
, END_PRODUCTION
// At index 29 : <definition_expression_factor>, in file 'sara_parser', line 913
, NONTERMINAL (25) // <select_sara_parser_16>
, END_PRODUCTION
// At index 31 : <definition_expression_factor>, in file 'sara_parser', line 1001
, TERMINAL (sara_scanner::sara_scanner_1_machineIdf) // $machineIdf$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (29) // <select_repeat_sara_parser_20>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, NONTERMINAL (30) // <select_sara_parser_21>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (32) // <select_repeat_sara_parser_23>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, END_PRODUCTION
// At index 44 : <component>, in file 'sara_parser', line 462
, TERMINAL (sara_scanner::sara_scanner_1_check) // $check$
, TERMINAL (sara_scanner::sara_scanner_1_machineIdf) // $machineIdf$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 48 : <component>, in file 'sara_parser', line 484
, TERMINAL (sara_scanner::sara_scanner_1_use_5Fand) // $use_and$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 51 : <component>, in file 'sara_parser', line 496
, TERMINAL (sara_scanner::sara_scanner_1_use_5Fite) // $use_ite$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 54 : <component>, in file 'sara_parser', line 508
, TERMINAL (sara_scanner::sara_scanner_1_use_5Fand_5Fite) // $use_and_ite$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 57 : <component>, in file 'sara_parser', line 520
, TERMINAL (sara_scanner::sara_scanner_1_and_5Fcache) // $and_cache$
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Finteger) // $literal_integer$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 61 : <component>, in file 'sara_parser', line 534
, TERMINAL (sara_scanner::sara_scanner_1_ite_5Fcache) // $ite_cache$
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Finteger) // $literal_integer$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 65 : <component>, in file 'sara_parser', line 548
, TERMINAL (sara_scanner::sara_scanner_1_map) // $map$
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Finteger) // $literal_integer$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 69 : <component>, in file 'sara_parser', line 562
, TERMINAL (sara_scanner::sara_scanner_1_bdd) // $bdd$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 72 : <component>, in file 'sara_parser', line 574
, TERMINAL (sara_scanner::sara_scanner_1_machineIdf) // $machineIdf$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (10) // <select_repeat_sara_parser_1>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, NONTERMINAL (11) // <select_sara_parser_2>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (13) // <select_repeat_sara_parser_4>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, TERMINAL (sara_scanner::sara_scanner_1__3A_3D) // $:=$
, NONTERMINAL (2) // <definition_expression>
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 88 : <component>, in file 'sara_parser', line 634
, TERMINAL (sara_scanner::sara_scanner_1_scenario) // $scenario$
, TERMINAL (sara_scanner::sara_scanner_1_machineIdf) // $machineIdf$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (14) // <select_repeat_sara_parser_5>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, NONTERMINAL (15) // <select_sara_parser_6>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (17) // <select_repeat_sara_parser_8>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, TERMINAL (sara_scanner::sara_scanner_1__7B) // ${$
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Fstring) // $literal_string$
, TERMINAL (sara_scanner::sara_scanner_1__3A) // $:$
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Finteger) // $literal_integer$
, NONTERMINAL (20) // <select_repeat_sara_parser_11>
, NONTERMINAL (19) // <select_repeat_sara_parser_10>
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, NONTERMINAL (18) // <select_repeat_sara_parser_9>
, TERMINAL (sara_scanner::sara_scanner_1__7D) // $}$
, END_PRODUCTION
// At index 111 : <io_expression>, in file 'sara_parser', line 740
, NONTERMINAL (7) // <io_and_expression>
, NONTERMINAL (21) // <select_repeat_sara_parser_12>
, END_PRODUCTION
// At index 114 : <io_and_expression>, in file 'sara_parser', line 771
, NONTERMINAL (8) // <io_primary>
, NONTERMINAL (22) // <select_repeat_sara_parser_13>
, END_PRODUCTION
// At index 117 : <io_primary>, in file 'sara_parser', line 787
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, NONTERMINAL (6) // <io_expression>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, END_PRODUCTION
// At index 121 : <io_primary>, in file 'sara_parser', line 798
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, END_PRODUCTION
// At index 123 : <io_primary>, in file 'sara_parser', line 811
, TERMINAL (sara_scanner::sara_scanner_1__21) // $!$
, NONTERMINAL (8) // <io_primary>
, END_PRODUCTION
// At index 126 : <io_primary>, in file 'sara_parser', line 823
, TERMINAL (sara_scanner::sara_scanner_1_none) // $none$
, END_PRODUCTION
// At index 128 : <io_primary>, in file 'sara_parser', line 833
, TERMINAL (sara_scanner::sara_scanner_1_all) // $all$
, END_PRODUCTION
//---- Added productions from 'select' and 'repeat' instructions
// At index 130 : <select_repeat_sara_parser_0>, in file 'sara_parser', line 454
, END_PRODUCTION
// At index 131 : <select_repeat_sara_parser_0>, in file 'sara_parser', line 454
, NONTERMINAL (5) // <component>
, NONTERMINAL (9) // <select_repeat_sara_parser_0>
, END_PRODUCTION
// At index 134 : <select_repeat_sara_parser_1>, in file 'sara_parser', line 587
, END_PRODUCTION
// At index 135 : <select_repeat_sara_parser_1>, in file 'sara_parser', line 587
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (10) // <select_repeat_sara_parser_1>
, END_PRODUCTION
// At index 139 : <select_sara_parser_2>, in file 'sara_parser', line 598
, END_PRODUCTION
// At index 140 : <select_sara_parser_2>, in file 'sara_parser', line 598
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (12) // <select_repeat_sara_parser_3>
, END_PRODUCTION
// At index 143 : <select_repeat_sara_parser_3>, in file 'sara_parser', line 600
, END_PRODUCTION
// At index 144 : <select_repeat_sara_parser_3>, in file 'sara_parser', line 600
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (12) // <select_repeat_sara_parser_3>
, END_PRODUCTION
// At index 148 : <select_repeat_sara_parser_4>, in file 'sara_parser', line 612
, END_PRODUCTION
// At index 149 : <select_repeat_sara_parser_4>, in file 'sara_parser', line 612
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (13) // <select_repeat_sara_parser_4>
, END_PRODUCTION
// At index 153 : <select_repeat_sara_parser_5>, in file 'sara_parser', line 654
, END_PRODUCTION
// At index 154 : <select_repeat_sara_parser_5>, in file 'sara_parser', line 654
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (14) // <select_repeat_sara_parser_5>
, END_PRODUCTION
// At index 158 : <select_sara_parser_6>, in file 'sara_parser', line 670
, END_PRODUCTION
// At index 159 : <select_sara_parser_6>, in file 'sara_parser', line 670
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (16) // <select_repeat_sara_parser_7>
, END_PRODUCTION
// At index 162 : <select_repeat_sara_parser_7>, in file 'sara_parser', line 672
, END_PRODUCTION
// At index 163 : <select_repeat_sara_parser_7>, in file 'sara_parser', line 672
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (16) // <select_repeat_sara_parser_7>
, END_PRODUCTION
// At index 167 : <select_repeat_sara_parser_8>, in file 'sara_parser', line 689
, END_PRODUCTION
// At index 168 : <select_repeat_sara_parser_8>, in file 'sara_parser', line 689
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (17) // <select_repeat_sara_parser_8>
, END_PRODUCTION
// At index 172 : <select_repeat_sara_parser_9>, in file 'sara_parser', line 706
, END_PRODUCTION
// At index 173 : <select_repeat_sara_parser_9>, in file 'sara_parser', line 706
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Fstring) // $literal_string$
, TERMINAL (sara_scanner::sara_scanner_1__3A) // $:$
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Finteger) // $literal_integer$
, NONTERMINAL (20) // <select_repeat_sara_parser_11>
, NONTERMINAL (19) // <select_repeat_sara_parser_10>
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, NONTERMINAL (18) // <select_repeat_sara_parser_9>
, END_PRODUCTION
// At index 181 : <select_repeat_sara_parser_10>, in file 'sara_parser', line 710
, END_PRODUCTION
// At index 182 : <select_repeat_sara_parser_10>, in file 'sara_parser', line 710
, TERMINAL (sara_scanner::sara_scanner_1__3A) // $:$
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Finteger) // $literal_integer$
, NONTERMINAL (20) // <select_repeat_sara_parser_11>
, NONTERMINAL (19) // <select_repeat_sara_parser_10>
, END_PRODUCTION
// At index 187 : <select_repeat_sara_parser_11>, in file 'sara_parser', line 713
, END_PRODUCTION
// At index 188 : <select_repeat_sara_parser_11>, in file 'sara_parser', line 713
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_literal_5Finteger) // $literal_integer$
, NONTERMINAL (20) // <select_repeat_sara_parser_11>
, END_PRODUCTION
// At index 192 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
, END_PRODUCTION
// At index 193 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
, TERMINAL (sara_scanner::sara_scanner_1__7C) // $|$
, NONTERMINAL (7) // <io_and_expression>
, NONTERMINAL (21) // <select_repeat_sara_parser_12>
, END_PRODUCTION
// At index 197 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
, TERMINAL (sara_scanner::sara_scanner_1__5E) // $^$
, NONTERMINAL (7) // <io_and_expression>
, NONTERMINAL (21) // <select_repeat_sara_parser_12>
, END_PRODUCTION
// At index 201 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
, TERMINAL (sara_scanner::sara_scanner_1__2D_3E) // $->$
, NONTERMINAL (7) // <io_and_expression>
, NONTERMINAL (21) // <select_repeat_sara_parser_12>
, END_PRODUCTION
// At index 205 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
, TERMINAL (sara_scanner::sara_scanner_1__3D) // $=$
, NONTERMINAL (7) // <io_and_expression>
, NONTERMINAL (21) // <select_repeat_sara_parser_12>
, END_PRODUCTION
// At index 209 : <select_repeat_sara_parser_13>, in file 'sara_parser', line 777
, END_PRODUCTION
// At index 210 : <select_repeat_sara_parser_13>, in file 'sara_parser', line 777
, TERMINAL (sara_scanner::sara_scanner_1__26) // $&$
, NONTERMINAL (8) // <io_primary>
, NONTERMINAL (22) // <select_repeat_sara_parser_13>
, END_PRODUCTION
// At index 214 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
, END_PRODUCTION
// At index 215 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
, TERMINAL (sara_scanner::sara_scanner_1__7C) // $|$
, NONTERMINAL (3) // <definition_expression_term>
, NONTERMINAL (23) // <select_repeat_sara_parser_14>
, END_PRODUCTION
// At index 219 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
, TERMINAL (sara_scanner::sara_scanner_1__5E) // $^$
, NONTERMINAL (3) // <definition_expression_term>
, NONTERMINAL (23) // <select_repeat_sara_parser_14>
, END_PRODUCTION
// At index 223 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
, TERMINAL (sara_scanner::sara_scanner_1__2D_3E) // $->$
, NONTERMINAL (3) // <definition_expression_term>
, NONTERMINAL (23) // <select_repeat_sara_parser_14>
, END_PRODUCTION
// At index 227 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
, TERMINAL (sara_scanner::sara_scanner_1__3D) // $=$
, NONTERMINAL (3) // <definition_expression_term>
, NONTERMINAL (23) // <select_repeat_sara_parser_14>
, END_PRODUCTION
// At index 231 : <select_repeat_sara_parser_15>, in file 'sara_parser', line 888
, END_PRODUCTION
// At index 232 : <select_repeat_sara_parser_15>, in file 'sara_parser', line 888
, TERMINAL (sara_scanner::sara_scanner_1__2A) // $*$
, NONTERMINAL (4) // <definition_expression_factor>
, NONTERMINAL (24) // <select_repeat_sara_parser_15>
, END_PRODUCTION
// At index 236 : <select_repeat_sara_parser_15>, in file 'sara_parser', line 888
, TERMINAL (sara_scanner::sara_scanner_1__2A_2A) // $**$
, NONTERMINAL (4) // <definition_expression_factor>
, NONTERMINAL (24) // <select_repeat_sara_parser_15>
, END_PRODUCTION
// At index 240 : <select_repeat_sara_parser_15>, in file 'sara_parser', line 888
, TERMINAL (sara_scanner::sara_scanner_1__26) // $&$
, NONTERMINAL (4) // <definition_expression_factor>
, NONTERMINAL (24) // <select_repeat_sara_parser_15>
, END_PRODUCTION
// At index 244 : <select_sara_parser_16>, in file 'sara_parser', line 919
, NONTERMINAL (1) // <explicit_automaton>
, END_PRODUCTION
// At index 246 : <select_sara_parser_16>, in file 'sara_parser', line 919
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, NONTERMINAL (2) // <definition_expression>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, END_PRODUCTION
// At index 250 : <select_sara_parser_16>, in file 'sara_parser', line 919
, TERMINAL (sara_scanner::sara_scanner_1__3F) // $?$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (26) // <select_repeat_sara_parser_17>
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, NONTERMINAL (2) // <definition_expression>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, END_PRODUCTION
// At index 257 : <select_sara_parser_16>, in file 'sara_parser', line 919
, TERMINAL (sara_scanner::sara_scanner_1__21) // $!$
, NONTERMINAL (4) // <definition_expression_factor>
, END_PRODUCTION
// At index 260 : <select_sara_parser_16>, in file 'sara_parser', line 919
, TERMINAL (sara_scanner::sara_scanner_1__40) // $@$
, NONTERMINAL (4) // <definition_expression_factor>
, END_PRODUCTION
// At index 263 : <select_sara_parser_16>, in file 'sara_parser', line 919
, TERMINAL (sara_scanner::sara_scanner_1_nolast) // $nolast$
, TERMINAL (sara_scanner::sara_scanner_1__28) // $($
, NONTERMINAL (2) // <definition_expression>
, TERMINAL (sara_scanner::sara_scanner_1__29) // $)$
, END_PRODUCTION
// At index 268 : <select_sara_parser_16>, in file 'sara_parser', line 919
, TERMINAL (sara_scanner::sara_scanner_1_modalcomp) // $modalcomp$
, TERMINAL (sara_scanner::sara_scanner_1__7B) // ${$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, TERMINAL (sara_scanner::sara_scanner_1__3A) // $:$
, NONTERMINAL (2) // <definition_expression>
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, NONTERMINAL (27) // <select_repeat_sara_parser_18>
, NONTERMINAL (28) // <select_repeat_sara_parser_19>
, TERMINAL (sara_scanner::sara_scanner_1__7D) // $}$
, END_PRODUCTION
// At index 278 : <select_sara_parser_16>, in file 'sara_parser', line 919
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, END_PRODUCTION
// At index 280 : <select_repeat_sara_parser_17>, in file 'sara_parser', line 929
, END_PRODUCTION
// At index 281 : <select_repeat_sara_parser_17>, in file 'sara_parser', line 929
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (26) // <select_repeat_sara_parser_17>
, END_PRODUCTION
// At index 285 : <select_repeat_sara_parser_18>, in file 'sara_parser', line 964
, END_PRODUCTION
// At index 286 : <select_repeat_sara_parser_18>, in file 'sara_parser', line 964
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, TERMINAL (sara_scanner::sara_scanner_1__3A) // $:$
, NONTERMINAL (2) // <definition_expression>
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, NONTERMINAL (27) // <select_repeat_sara_parser_18>
, END_PRODUCTION
// At index 292 : <select_repeat_sara_parser_19>, in file 'sara_parser', line 974
, END_PRODUCTION
// At index 293 : <select_repeat_sara_parser_19>, in file 'sara_parser', line 974
, TERMINAL (sara_scanner::sara_scanner_1_exclude) // $exclude$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, TERMINAL (sara_scanner::sara_scanner_1_to) // $to$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, NONTERMINAL (28) // <select_repeat_sara_parser_19>
, END_PRODUCTION
// At index 300 : <select_repeat_sara_parser_20>, in file 'sara_parser', line 1017
, END_PRODUCTION
// At index 301 : <select_repeat_sara_parser_20>, in file 'sara_parser', line 1017
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (29) // <select_repeat_sara_parser_20>
, END_PRODUCTION
// At index 305 : <select_sara_parser_21>, in file 'sara_parser', line 1034
, END_PRODUCTION
// At index 306 : <select_sara_parser_21>, in file 'sara_parser', line 1034
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (31) // <select_repeat_sara_parser_22>
, END_PRODUCTION
// At index 309 : <select_repeat_sara_parser_22>, in file 'sara_parser', line 1036
, END_PRODUCTION
// At index 310 : <select_repeat_sara_parser_22>, in file 'sara_parser', line 1036
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (31) // <select_repeat_sara_parser_22>
, END_PRODUCTION
// At index 314 : <select_repeat_sara_parser_23>, in file 'sara_parser', line 1054
, END_PRODUCTION
// At index 315 : <select_repeat_sara_parser_23>, in file 'sara_parser', line 1054
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (32) // <select_repeat_sara_parser_23>
, END_PRODUCTION
// At index 319 : <select_repeat_sara_parser_24>, in file 'sara_parser', line 1087
, END_PRODUCTION
// At index 320 : <select_repeat_sara_parser_24>, in file 'sara_parser', line 1087
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (33) // <select_repeat_sara_parser_24>
, END_PRODUCTION
// At index 324 : <select_repeat_sara_parser_25>, in file 'sara_parser', line 1098
, END_PRODUCTION
// At index 325 : <select_repeat_sara_parser_25>, in file 'sara_parser', line 1098
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (34) // <select_repeat_sara_parser_25>
, END_PRODUCTION
// At index 329 : <select_sara_parser_26>, in file 'sara_parser', line 1110
, END_PRODUCTION
// At index 330 : <select_sara_parser_26>, in file 'sara_parser', line 1110
, TERMINAL (sara_scanner::sara_scanner_1_last) // $last$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (36) // <select_repeat_sara_parser_27>
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, END_PRODUCTION
// At index 335 : <select_repeat_sara_parser_27>, in file 'sara_parser', line 1113
, END_PRODUCTION
// At index 336 : <select_repeat_sara_parser_27>, in file 'sara_parser', line 1113
, TERMINAL (sara_scanner::sara_scanner_1__2C) // $,$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, NONTERMINAL (36) // <select_repeat_sara_parser_27>
, END_PRODUCTION
// At index 340 : <select_repeat_sara_parser_28>, in file 'sara_parser', line 1126
, END_PRODUCTION
// At index 341 : <select_repeat_sara_parser_28>, in file 'sara_parser', line 1126
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, TERMINAL (sara_scanner::sara_scanner_1__3A) // $:$
, NONTERMINAL (6) // <io_expression>
, TERMINAL (sara_scanner::sara_scanner_1__7B) // ${$
, NONTERMINAL (38) // <select_repeat_sara_parser_29>
, TERMINAL (sara_scanner::sara_scanner_1__7D) // $}$
, NONTERMINAL (37) // <select_repeat_sara_parser_28>
, END_PRODUCTION
// At index 349 : <select_repeat_sara_parser_29>, in file 'sara_parser', line 1141
, END_PRODUCTION
// At index 350 : <select_repeat_sara_parser_29>, in file 'sara_parser', line 1141
, NONTERMINAL (6) // <io_expression>
, TERMINAL (sara_scanner::sara_scanner_1_goto) // $goto$
, TERMINAL (sara_scanner::sara_scanner_1_identifier) // $identifier$
, TERMINAL (sara_scanner::sara_scanner_1__3B) // $;$
, NONTERMINAL (38) // <select_repeat_sara_parser_29>
, END_PRODUCTION
// At index 356 : <>, in file '', line 0
, NONTERMINAL (0) // <start_symbol>
, END_PRODUCTION
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//            L L ( 1 )    P R O D U C T I O N    I N D E X E S              *
//                                                                           *
//---------------------------------------------------------------------------*

static const sint16 gProductionIndexes [98] = {
0, // index 0 : <start_symbol>, in file 'sara_parser', line 449
3, // index 1 : <explicit_automaton>, in file 'sara_parser', line 1076
23, // index 2 : <definition_expression>, in file 'sara_parser', line 845
26, // index 3 : <definition_expression_term>, in file 'sara_parser', line 881
29, // index 4 : <definition_expression_factor>, in file 'sara_parser', line 913
31, // index 5 : <definition_expression_factor>, in file 'sara_parser', line 1001
44, // index 6 : <component>, in file 'sara_parser', line 462
48, // index 7 : <component>, in file 'sara_parser', line 484
51, // index 8 : <component>, in file 'sara_parser', line 496
54, // index 9 : <component>, in file 'sara_parser', line 508
57, // index 10 : <component>, in file 'sara_parser', line 520
61, // index 11 : <component>, in file 'sara_parser', line 534
65, // index 12 : <component>, in file 'sara_parser', line 548
69, // index 13 : <component>, in file 'sara_parser', line 562
72, // index 14 : <component>, in file 'sara_parser', line 574
88, // index 15 : <component>, in file 'sara_parser', line 634
111, // index 16 : <io_expression>, in file 'sara_parser', line 740
114, // index 17 : <io_and_expression>, in file 'sara_parser', line 771
117, // index 18 : <io_primary>, in file 'sara_parser', line 787
121, // index 19 : <io_primary>, in file 'sara_parser', line 798
123, // index 20 : <io_primary>, in file 'sara_parser', line 811
126, // index 21 : <io_primary>, in file 'sara_parser', line 823
128, // index 22 : <io_primary>, in file 'sara_parser', line 833
130, // index 23 : <select_repeat_sara_parser_0>, in file 'sara_parser', line 454
131, // index 24 : <select_repeat_sara_parser_0>, in file 'sara_parser', line 454
134, // index 25 : <select_repeat_sara_parser_1>, in file 'sara_parser', line 587
135, // index 26 : <select_repeat_sara_parser_1>, in file 'sara_parser', line 587
139, // index 27 : <select_sara_parser_2>, in file 'sara_parser', line 598
140, // index 28 : <select_sara_parser_2>, in file 'sara_parser', line 598
143, // index 29 : <select_repeat_sara_parser_3>, in file 'sara_parser', line 600
144, // index 30 : <select_repeat_sara_parser_3>, in file 'sara_parser', line 600
148, // index 31 : <select_repeat_sara_parser_4>, in file 'sara_parser', line 612
149, // index 32 : <select_repeat_sara_parser_4>, in file 'sara_parser', line 612
153, // index 33 : <select_repeat_sara_parser_5>, in file 'sara_parser', line 654
154, // index 34 : <select_repeat_sara_parser_5>, in file 'sara_parser', line 654
158, // index 35 : <select_sara_parser_6>, in file 'sara_parser', line 670
159, // index 36 : <select_sara_parser_6>, in file 'sara_parser', line 670
162, // index 37 : <select_repeat_sara_parser_7>, in file 'sara_parser', line 672
163, // index 38 : <select_repeat_sara_parser_7>, in file 'sara_parser', line 672
167, // index 39 : <select_repeat_sara_parser_8>, in file 'sara_parser', line 689
168, // index 40 : <select_repeat_sara_parser_8>, in file 'sara_parser', line 689
172, // index 41 : <select_repeat_sara_parser_9>, in file 'sara_parser', line 706
173, // index 42 : <select_repeat_sara_parser_9>, in file 'sara_parser', line 706
181, // index 43 : <select_repeat_sara_parser_10>, in file 'sara_parser', line 710
182, // index 44 : <select_repeat_sara_parser_10>, in file 'sara_parser', line 710
187, // index 45 : <select_repeat_sara_parser_11>, in file 'sara_parser', line 713
188, // index 46 : <select_repeat_sara_parser_11>, in file 'sara_parser', line 713
192, // index 47 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
193, // index 48 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
197, // index 49 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
201, // index 50 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
205, // index 51 : <select_repeat_sara_parser_12>, in file 'sara_parser', line 746
209, // index 52 : <select_repeat_sara_parser_13>, in file 'sara_parser', line 777
210, // index 53 : <select_repeat_sara_parser_13>, in file 'sara_parser', line 777
214, // index 54 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
215, // index 55 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
219, // index 56 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
223, // index 57 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
227, // index 58 : <select_repeat_sara_parser_14>, in file 'sara_parser', line 852
231, // index 59 : <select_repeat_sara_parser_15>, in file 'sara_parser', line 888
232, // index 60 : <select_repeat_sara_parser_15>, in file 'sara_parser', line 888
236, // index 61 : <select_repeat_sara_parser_15>, in file 'sara_parser', line 888
240, // index 62 : <select_repeat_sara_parser_15>, in file 'sara_parser', line 888
244, // index 63 : <select_sara_parser_16>, in file 'sara_parser', line 919
246, // index 64 : <select_sara_parser_16>, in file 'sara_parser', line 919
250, // index 65 : <select_sara_parser_16>, in file 'sara_parser', line 919
257, // index 66 : <select_sara_parser_16>, in file 'sara_parser', line 919
260, // index 67 : <select_sara_parser_16>, in file 'sara_parser', line 919
263, // index 68 : <select_sara_parser_16>, in file 'sara_parser', line 919
268, // index 69 : <select_sara_parser_16>, in file 'sara_parser', line 919
278, // index 70 : <select_sara_parser_16>, in file 'sara_parser', line 919
280, // index 71 : <select_repeat_sara_parser_17>, in file 'sara_parser', line 929
281, // index 72 : <select_repeat_sara_parser_17>, in file 'sara_parser', line 929
285, // index 73 : <select_repeat_sara_parser_18>, in file 'sara_parser', line 964
286, // index 74 : <select_repeat_sara_parser_18>, in file 'sara_parser', line 964
292, // index 75 : <select_repeat_sara_parser_19>, in file 'sara_parser', line 974
293, // index 76 : <select_repeat_sara_parser_19>, in file 'sara_parser', line 974
300, // index 77 : <select_repeat_sara_parser_20>, in file 'sara_parser', line 1017
301, // index 78 : <select_repeat_sara_parser_20>, in file 'sara_parser', line 1017
305, // index 79 : <select_sara_parser_21>, in file 'sara_parser', line 1034
306, // index 80 : <select_sara_parser_21>, in file 'sara_parser', line 1034
309, // index 81 : <select_repeat_sara_parser_22>, in file 'sara_parser', line 1036
310, // index 82 : <select_repeat_sara_parser_22>, in file 'sara_parser', line 1036
314, // index 83 : <select_repeat_sara_parser_23>, in file 'sara_parser', line 1054
315, // index 84 : <select_repeat_sara_parser_23>, in file 'sara_parser', line 1054
319, // index 85 : <select_repeat_sara_parser_24>, in file 'sara_parser', line 1087
320, // index 86 : <select_repeat_sara_parser_24>, in file 'sara_parser', line 1087
324, // index 87 : <select_repeat_sara_parser_25>, in file 'sara_parser', line 1098
325, // index 88 : <select_repeat_sara_parser_25>, in file 'sara_parser', line 1098
329, // index 89 : <select_sara_parser_26>, in file 'sara_parser', line 1110
330, // index 90 : <select_sara_parser_26>, in file 'sara_parser', line 1110
335, // index 91 : <select_repeat_sara_parser_27>, in file 'sara_parser', line 1113
336, // index 92 : <select_repeat_sara_parser_27>, in file 'sara_parser', line 1113
340, // index 93 : <select_repeat_sara_parser_28>, in file 'sara_parser', line 1126
341, // index 94 : <select_repeat_sara_parser_28>, in file 'sara_parser', line 1126
349, // index 95 : <select_repeat_sara_parser_29>, in file 'sara_parser', line 1141
350, // index 96 : <select_repeat_sara_parser_29>, in file 'sara_parser', line 1141
356 // index 97 : <>, in file '', line 0
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//      L L ( 1 )    F I R S T    P R O D U C T I O N    I N D E X E S       *
//                                                                           *
//---------------------------------------------------------------------------*

static const sint16 gFirstProductionIndexes [41] = {
0, // at 0 : <start_symbol>
1, // at 1 : <explicit_automaton>
2, // at 2 : <definition_expression>
3, // at 3 : <definition_expression_term>
4, // at 4 : <definition_expression_factor>
6, // at 5 : <component>
16, // at 6 : <io_expression>
17, // at 7 : <io_and_expression>
18, // at 8 : <io_primary>
23, // at 9 : <select_repeat_sara_parser_0>
25, // at 10 : <select_repeat_sara_parser_1>
27, // at 11 : <select_sara_parser_2>
29, // at 12 : <select_repeat_sara_parser_3>
31, // at 13 : <select_repeat_sara_parser_4>
33, // at 14 : <select_repeat_sara_parser_5>
35, // at 15 : <select_sara_parser_6>
37, // at 16 : <select_repeat_sara_parser_7>
39, // at 17 : <select_repeat_sara_parser_8>
41, // at 18 : <select_repeat_sara_parser_9>
43, // at 19 : <select_repeat_sara_parser_10>
45, // at 20 : <select_repeat_sara_parser_11>
47, // at 21 : <select_repeat_sara_parser_12>
52, // at 22 : <select_repeat_sara_parser_13>
54, // at 23 : <select_repeat_sara_parser_14>
59, // at 24 : <select_repeat_sara_parser_15>
63, // at 25 : <select_sara_parser_16>
71, // at 26 : <select_repeat_sara_parser_17>
73, // at 27 : <select_repeat_sara_parser_18>
75, // at 28 : <select_repeat_sara_parser_19>
77, // at 29 : <select_repeat_sara_parser_20>
79, // at 30 : <select_sara_parser_21>
81, // at 31 : <select_repeat_sara_parser_22>
83, // at 32 : <select_repeat_sara_parser_23>
85, // at 33 : <select_repeat_sara_parser_24>
87, // at 34 : <select_repeat_sara_parser_25>
89, // at 35 : <select_sara_parser_26>
91, // at 36 : <select_repeat_sara_parser_27>
93, // at 37 : <select_repeat_sara_parser_28>
95, // at 38 : <select_repeat_sara_parser_29>
97, // at 39 : <>
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//               L L ( 1 )    D E C I S I O N    T A B L E S                 *
//                                                                           *
//---------------------------------------------------------------------------*

static const sint16 gDecision [] = {
// At index 0 : <start_symbol> only one production, no choice
  -1,
// At index 1 : <explicit_automaton> only one production, no choice
  -1,
// At index 2 : <definition_expression> only one production, no choice
  -1,
// At index 3 : <definition_expression_term> only one production, no choice
  -1,
// At index 4 : <definition_expression_factor>
sara_scanner::sara_scanner_1_identifier, sara_scanner::sara_scanner_1_auto, sara_scanner::sara_scanner_1_nolast, sara_scanner::sara_scanner_1_modalcomp, sara_scanner::sara_scanner_1__21, sara_scanner::sara_scanner_1__3F, sara_scanner::sara_scanner_1__28, sara_scanner::sara_scanner_1__40, -1, // Choice 1
sara_scanner::sara_scanner_1_machineIdf, -1, // Choice 2
  -1,
// At index 16 : <component>
sara_scanner::sara_scanner_1_check, -1, // Choice 1
sara_scanner::sara_scanner_1_use_5Fand, -1, // Choice 2
sara_scanner::sara_scanner_1_use_5Fite, -1, // Choice 3
sara_scanner::sara_scanner_1_use_5Fand_5Fite, -1, // Choice 4
sara_scanner::sara_scanner_1_and_5Fcache, -1, // Choice 5
sara_scanner::sara_scanner_1_ite_5Fcache, -1, // Choice 6
sara_scanner::sara_scanner_1_map, -1, // Choice 7
sara_scanner::sara_scanner_1_bdd, -1, // Choice 8
sara_scanner::sara_scanner_1_machineIdf, -1, // Choice 9
sara_scanner::sara_scanner_1_scenario, -1, // Choice 10
  -1,
// At index 37 : <io_expression> only one production, no choice
  -1,
// At index 38 : <io_and_expression> only one production, no choice
  -1,
// At index 39 : <io_primary>
sara_scanner::sara_scanner_1__28, -1, // Choice 1
sara_scanner::sara_scanner_1_identifier, -1, // Choice 2
sara_scanner::sara_scanner_1__21, -1, // Choice 3
sara_scanner::sara_scanner_1_none, -1, // Choice 4
sara_scanner::sara_scanner_1_all, -1, // Choice 5
  -1,
//---- Added non terminal symbols from 'select' and 'repeat' instructions
// At index 50 : <select_repeat_sara_parser_0>
sara_scanner::sara_scanner_1_, -1, // Choice 1
sara_scanner::sara_scanner_1_check, sara_scanner::sara_scanner_1_scenario, sara_scanner::sara_scanner_1_ite_5Fcache, sara_scanner::sara_scanner_1_and_5Fcache, sara_scanner::sara_scanner_1_map, sara_scanner::sara_scanner_1_bdd, sara_scanner::sara_scanner_1_use_5Fand, sara_scanner::sara_scanner_1_use_5Fite, sara_scanner::sara_scanner_1_use_5Fand_5Fite, sara_scanner::sara_scanner_1_machineIdf, -1, // Choice 2
  -1,
// At index 64 : <select_repeat_sara_parser_1>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 69 : <select_sara_parser_2>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1_identifier, -1, // Choice 2
  -1,
// At index 74 : <select_repeat_sara_parser_3>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 79 : <select_repeat_sara_parser_4>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 84 : <select_repeat_sara_parser_5>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 89 : <select_sara_parser_6>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1_identifier, -1, // Choice 2
  -1,
// At index 94 : <select_repeat_sara_parser_7>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 99 : <select_repeat_sara_parser_8>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 104 : <select_repeat_sara_parser_9>
sara_scanner::sara_scanner_1__7D, -1, // Choice 1
sara_scanner::sara_scanner_1_literal_5Fstring, -1, // Choice 2
  -1,
// At index 109 : <select_repeat_sara_parser_10>
sara_scanner::sara_scanner_1__3B, -1, // Choice 1
sara_scanner::sara_scanner_1__3A, -1, // Choice 2
  -1,
// At index 114 : <select_repeat_sara_parser_11>
sara_scanner::sara_scanner_1__3B, sara_scanner::sara_scanner_1__3A, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 120 : <select_repeat_sara_parser_12>
sara_scanner::sara_scanner_1_goto, sara_scanner::sara_scanner_1__7B, sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__7C, -1, // Choice 2
sara_scanner::sara_scanner_1__5E, -1, // Choice 3
sara_scanner::sara_scanner_1__2D_3E, -1, // Choice 4
sara_scanner::sara_scanner_1__3D, -1, // Choice 5
  -1,
// At index 133 : <select_repeat_sara_parser_13>
sara_scanner::sara_scanner_1_goto, sara_scanner::sara_scanner_1__7B, sara_scanner::sara_scanner_1__2D_3E, sara_scanner::sara_scanner_1__7C, sara_scanner::sara_scanner_1__29, sara_scanner::sara_scanner_1__5E, sara_scanner::sara_scanner_1__3D, -1, // Choice 1
sara_scanner::sara_scanner_1__26, -1, // Choice 2
  -1,
// At index 144 : <select_repeat_sara_parser_14>
sara_scanner::sara_scanner_1__3B, sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__7C, -1, // Choice 2
sara_scanner::sara_scanner_1__5E, -1, // Choice 3
sara_scanner::sara_scanner_1__2D_3E, -1, // Choice 4
sara_scanner::sara_scanner_1__3D, -1, // Choice 5
  -1,
// At index 156 : <select_repeat_sara_parser_15>
sara_scanner::sara_scanner_1__3B, sara_scanner::sara_scanner_1__2D_3E, sara_scanner::sara_scanner_1__7C, sara_scanner::sara_scanner_1__29, sara_scanner::sara_scanner_1__5E, sara_scanner::sara_scanner_1__3D, -1, // Choice 1
sara_scanner::sara_scanner_1__2A, -1, // Choice 2
sara_scanner::sara_scanner_1__2A_2A, -1, // Choice 3
sara_scanner::sara_scanner_1__26, -1, // Choice 4
  -1,
// At index 170 : <select_sara_parser_16>
sara_scanner::sara_scanner_1_auto, -1, // Choice 1
sara_scanner::sara_scanner_1__28, -1, // Choice 2
sara_scanner::sara_scanner_1__3F, -1, // Choice 3
sara_scanner::sara_scanner_1__21, -1, // Choice 4
sara_scanner::sara_scanner_1__40, -1, // Choice 5
sara_scanner::sara_scanner_1_nolast, -1, // Choice 6
sara_scanner::sara_scanner_1_modalcomp, -1, // Choice 7
sara_scanner::sara_scanner_1_identifier, -1, // Choice 8
  -1,
// At index 187 : <select_repeat_sara_parser_17>
sara_scanner::sara_scanner_1__28, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 192 : <select_repeat_sara_parser_18>
sara_scanner::sara_scanner_1_exclude, sara_scanner::sara_scanner_1__7D, -1, // Choice 1
sara_scanner::sara_scanner_1_identifier, -1, // Choice 2
  -1,
// At index 198 : <select_repeat_sara_parser_19>
sara_scanner::sara_scanner_1__7D, -1, // Choice 1
sara_scanner::sara_scanner_1_exclude, -1, // Choice 2
  -1,
// At index 203 : <select_repeat_sara_parser_20>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 208 : <select_sara_parser_21>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1_identifier, -1, // Choice 2
  -1,
// At index 213 : <select_repeat_sara_parser_22>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 218 : <select_repeat_sara_parser_23>
sara_scanner::sara_scanner_1__29, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 223 : <select_repeat_sara_parser_24>
sara_scanner::sara_scanner_1__3B, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 228 : <select_repeat_sara_parser_25>
sara_scanner::sara_scanner_1__3B, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 233 : <select_sara_parser_26>
sara_scanner::sara_scanner_1_identifier, -1, // Choice 1
sara_scanner::sara_scanner_1_last, -1, // Choice 2
  -1,
// At index 238 : <select_repeat_sara_parser_27>
sara_scanner::sara_scanner_1__3B, -1, // Choice 1
sara_scanner::sara_scanner_1__2C, -1, // Choice 2
  -1,
// At index 243 : <select_repeat_sara_parser_28>
sara_scanner::sara_scanner_1__7D, -1, // Choice 1
sara_scanner::sara_scanner_1_identifier, -1, // Choice 2
  -1,
// At index 248 : <select_repeat_sara_parser_29>
sara_scanner::sara_scanner_1__7D, -1, // Choice 1
sara_scanner::sara_scanner_1_identifier, sara_scanner::sara_scanner_1_all, sara_scanner::sara_scanner_1_none, sara_scanner::sara_scanner_1__21, sara_scanner::sara_scanner_1__28, -1, // Choice 2
  -1,
// At index 257 : <> only one production, no choice
  -1,
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//       L L ( 1 )    D E C I S I O N    T A B L E S    I N D E X E S        *
//                                                                           *
//---------------------------------------------------------------------------*

static const sint16 gDecisionIndexes [41] = {
0, // at 0 : <start_symbol>
1, // at 1 : <explicit_automaton>
2, // at 2 : <definition_expression>
3, // at 3 : <definition_expression_term>
4, // at 4 : <definition_expression_factor>
16, // at 5 : <component>
37, // at 6 : <io_expression>
38, // at 7 : <io_and_expression>
39, // at 8 : <io_primary>
50, // at 9 : <select_repeat_sara_parser_0>
64, // at 10 : <select_repeat_sara_parser_1>
69, // at 11 : <select_sara_parser_2>
74, // at 12 : <select_repeat_sara_parser_3>
79, // at 13 : <select_repeat_sara_parser_4>
84, // at 14 : <select_repeat_sara_parser_5>
89, // at 15 : <select_sara_parser_6>
94, // at 16 : <select_repeat_sara_parser_7>
99, // at 17 : <select_repeat_sara_parser_8>
104, // at 18 : <select_repeat_sara_parser_9>
109, // at 19 : <select_repeat_sara_parser_10>
114, // at 20 : <select_repeat_sara_parser_11>
120, // at 21 : <select_repeat_sara_parser_12>
133, // at 22 : <select_repeat_sara_parser_13>
144, // at 23 : <select_repeat_sara_parser_14>
156, // at 24 : <select_repeat_sara_parser_15>
170, // at 25 : <select_sara_parser_16>
187, // at 26 : <select_repeat_sara_parser_17>
192, // at 27 : <select_repeat_sara_parser_18>
198, // at 28 : <select_repeat_sara_parser_19>
203, // at 29 : <select_repeat_sara_parser_20>
208, // at 30 : <select_sara_parser_21>
213, // at 31 : <select_repeat_sara_parser_22>
218, // at 32 : <select_repeat_sara_parser_23>
223, // at 33 : <select_repeat_sara_parser_24>
228, // at 34 : <select_repeat_sara_parser_25>
233, // at 35 : <select_sara_parser_26>
238, // at 36 : <select_repeat_sara_parser_27>
243, // at 37 : <select_repeat_sara_parser_28>
248, // at 38 : <select_repeat_sara_parser_29>
257, // at 39 : <>
0} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                'start_symbol' non terminal implementation                 *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_start_symbol_ (sara_scanner & lexique_var_) {
  pr_start_symbol_sara_parser_449_20_ (lexique_var_) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                   Grammar start symbol implementation                     *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::startParsing_ (sara_scanner & lexique_var_) {
// classesCount : 0
  const bool ok = lexique_var_.performTopDownParsing (gProductions, gProductionIndexes,
                                gFirstProductionIndexes, gDecision, gDecisionIndexes, 356) ;
  if (ok && ! lexique_var_.parseOnlyFlagOn ()) {
    nt_start_symbol_ (lexique_var_) ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//             'explicit_automaton' non terminal implementation              *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_explicit_automaton_ (sara_scanner & lexique_var_,
                                GGS_M_variablesMap & parameter_1,
                                GGS_AC_machineDefinition & parameter_2) {
  pr_explicit_automaton_sara_parser_1076_26_ (lexique_var_, parameter_1, parameter_2) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//           'definition_expression' non terminal implementation             *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_definition_expression_ (sara_scanner & lexique_var_,
                                GGS_M_machinesMap & parameter_1,
                                GGS_M_variablesMap & parameter_2,
                                GGS_AC_machineDefinition & parameter_3) {
  pr_definition_expression_sara_parser_845_29_ (lexique_var_, parameter_1, parameter_2, parameter_3) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//         'definition_expression_term' non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_definition_expression_term_ (sara_scanner & lexique_var_,
                                GGS_M_machinesMap & parameter_1,
                                GGS_M_variablesMap & parameter_2,
                                GGS_AC_machineDefinition & parameter_3) {
  pr_definition_expression_term_sara_parser_881_34_ (lexique_var_, parameter_1, parameter_2, parameter_3) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'definition_expression_factor' non terminal implementation         *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_definition_expression_factor_ (sara_scanner & lexique_var_,
                                GGS_M_machinesMap & parameter_1,
                                GGS_M_variablesMap & parameter_2,
                                GGS_AC_machineDefinition & parameter_3) {
  switch (lexique_var_.getNextProductionIndex ()) {
  case 1 :
    pr_definition_expression_factor_sara_parser_913_36_ (lexique_var_, parameter_1, parameter_2, parameter_3) ;
    break ;
  case 2 :
    pr_definition_expression_factor_sara_parser_1001_36_ (lexique_var_, parameter_1, parameter_2, parameter_3) ;
    break ;
  default :
    break ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//                 'component' non terminal implementation                   *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_component_ (sara_scanner & lexique_var_,
                                GGS_M_machinesMap & parameter_1,
                                GGS_L_jobList & parameter_2) {
  switch (lexique_var_.getNextProductionIndex ()) {
  case 1 :
    pr_component_sara_parser_462_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 2 :
    pr_component_sara_parser_484_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 3 :
    pr_component_sara_parser_496_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 4 :
    pr_component_sara_parser_508_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 5 :
    pr_component_sara_parser_520_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 6 :
    pr_component_sara_parser_534_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 7 :
    pr_component_sara_parser_548_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 8 :
    pr_component_sara_parser_562_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 9 :
    pr_component_sara_parser_574_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 10 :
    pr_component_sara_parser_634_17_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  default :
    break ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//               'io_expression' non terminal implementation                 *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_io_expression_ (sara_scanner & lexique_var_,
                                GGS_M_variablesMap & parameter_1,
                                GGS_AC_expression & parameter_2) {
  pr_io_expression_sara_parser_740_21_ (lexique_var_, parameter_1, parameter_2) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//             'io_and_expression' non terminal implementation               *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_io_and_expression_ (sara_scanner & lexique_var_,
                                GGS_M_variablesMap & parameter_1,
                                GGS_AC_expression & parameter_2) {
  pr_io_and_expression_sara_parser_771_25_ (lexique_var_, parameter_1, parameter_2) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                 'io_primary' non terminal implementation                  *
//                                                                           *
//---------------------------------------------------------------------------*


void sara_grammar::nt_io_primary_ (sara_scanner & lexique_var_,
                                GGS_M_variablesMap & parameter_1,
                                GGS_AC_expression & parameter_2) {
  switch (lexique_var_.getNextProductionIndex ()) {
  case 1 :
    pr_io_primary_sara_parser_787_18_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 2 :
    pr_io_primary_sara_parser_798_18_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 3 :
    pr_io_primary_sara_parser_811_18_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 4 :
    pr_io_primary_sara_parser_823_18_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  case 5 :
    pr_io_primary_sara_parser_833_18_ (lexique_var_, parameter_1, parameter_2) ;
    break ;
  default :
    break ;
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_0' added non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_0 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_1' added non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_1 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//         'select_sara_parser_2' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_sara_parser_2 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_3' added non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_3 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_4' added non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_4 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_5' added non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_5 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//         'select_sara_parser_6' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_sara_parser_6 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_7' added non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_7 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_8' added non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_8 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_9' added non terminal implementation       *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_9 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_10' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_10 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_11' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_11 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_12' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_12 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_13' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_13 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_14' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_14 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_15' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_15 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_sara_parser_16' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_sara_parser_16 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_17' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_17 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_18' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_18 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_19' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_19 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_20' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_20 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_sara_parser_21' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_sara_parser_21 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_22' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_22 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_23' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_23 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_24' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_24 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_25' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_25 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//        'select_sara_parser_26' added non terminal implementation          *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_sara_parser_26 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_27' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_27 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_28' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_28 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//     'select_repeat_sara_parser_29' added non terminal implementation      *
//                                                                           *
//---------------------------------------------------------------------------*


sint16 sara_grammar::select_repeat_sara_parser_29 (sara_scanner & lexique_var_) {
  return lexique_var_.getNextProductionIndex () ;
}

//---------------------------------------------------------------------------*

