//---------------------------------------------------------------------------*
//                                                                           *
//                        File 'sara_cli_options.h'                          *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                       july 10th, 2009, at 17h0'30"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef sara_cli_options_0_DEFINED
#define sara_cli_options_0_DEFINED

//---------------------------------------------------------------------------*

#include "command_line_interface/C_BoolCommandLineOption.h"
#include "command_line_interface/C_UIntCommandLineOption.h"
#include "command_line_interface/C_StringCommandLineOption.h"

//---------------------------------------------------------------------------*

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


//---------------------------------------------------------------------------*
//                                                                           *
//                               Bool options                                *
//                                                                           *
//---------------------------------------------------------------------------*

extern C_BoolCommandLineOption gOption_sara_5F_cli_5F_options_displayBDDvalues ;

extern C_BoolCommandLineOption gOption_sara_5F_cli_5F_options_displayBDDvaluesCount ;

//---------------------------------------------------------------------------*
//                                                                           *
//                               UInt options                                *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*
//                                                                           *
//                              String options                               *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*

#endif
