//---------------------------------------------------------------------------*
//                                                                           *
//                            File 'sara_main.h'                             *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     january 24th, 2010, at 10h11'23"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef INTERFACE_sara_main_DEFINED
#define INTERFACE_sara_main_DEFINED

//---------------------------------------------------------------------------*

#include "sara_cli_options.h"
#include "galgas/C_galgas_CLI_Options.h"
#include "galgas-utilities/C_Lexique.h"
#include "command_line_interface/C_builtin_CLI_Options.h"

//---------------------------------------------------------------------------*

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*

#endif
