//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'sara_scanner.h'                            *
//               Generated by version 0.14.1 (LL(1) grammar)                 *
//                     february 2nd, 2005, at 15h58'37"                      *
//                                                                           *
// This program is free software; you can redistribute it and/or modify it   *
// under the terms of the GNU General Public License as published by the     *
// Free Software Foundation.                                                 *
//                                                                           *
// This program is distributed in the hope it will be useful, but WITHOUT    *
// ANY WARRANTY; without even the implied warranty of MERCHANDIBILITY or     *
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for  *
// more details.                                                             *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef sara_scanner_0_DEFINED
#define sara_scanner_0_DEFINED
#include "galgas/C_lexique.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//---------------------------------------------------------------------------*
//                                                                           *
//                          Lexical scanner class                            *
//                                                                           *
//---------------------------------------------------------------------------*

class sara_scanner : public C_lexique {
// Terminal symbols enumeration
  public : enum {sara_scanner_1_,
  sara_scanner_1_identifier,
  sara_scanner_1_auto,
  sara_scanner_1_state,
  sara_scanner_1_first,
  sara_scanner_1_goto,
  sara_scanner_1_timer,
  sara_scanner_1_true,
  sara_scanner_1_false,
  sara_scanner_1__2C,
  sara_scanner_1__3B,
  sara_scanner_1__3A,
  sara_scanner_1__7B,
  sara_scanner_1__7D,
  sara_scanner_1__2D_3E,
  sara_scanner_1__26,
  sara_scanner_1__21,
  sara_scanner_1__7C,
  sara_scanner_1__28,
  sara_scanner_1__29,
  sara_scanner_1__3A_3D,
  sara_scanner_1_literal_5Finteger} ;

//--- Key words table 'keyWordList'
  public : static const sint16 sara_scanner_table_size_keyWordList ;
  private : static const C_lexique_table_entry sara_scanner_table_for_keyWordList [7] ;
  public : static sint16 search_into_keyWordList (const C_string & inSearchedString) ;

//--- Key words table 'delimitorsList'
  public : static const sint16 sara_scanner_table_size_delimitorsList ;
  private : static const C_lexique_table_entry sara_scanner_table_for_delimitorsList [12] ;
  public : static sint16 search_into_delimitorsList (const C_string & inSearchedString) ;

  protected : virtual void parseLexicalToken (const bool inPropagateLexicaleErrorException) ;
  protected : virtual void appendTerminalMessageToSyntaxErrorMessage (const sint16 numeroTerminal,
                                                              C_string & messageErreur) ;

//--- Constructor
  public : sara_scanner (AC_galgas_io * inGalgasInputOutput) ;
  public : uint32 ulongValue ; // user defined attribute
  public : C_string identifierString ; // user defined attribute
  public : virtual sint16 getTerminalVocabularyCount_ (void) const { return 21 ; }

  public : static sint32 getStylesCount (void) ;
  public : static const char * getStyleName (const sint32 inIndex) ;
//--- Virtual method called getting terminal style index
  public : virtual uint8 getTerminalStyleIndex (const sint32 inTerminal) ;
} ;

//---------------------------------------------------------------------------*

#endif
