//---------------------------------------------------------------------------*
//                                                                           *
//                       File 'sara_cli_options.cpp'                         *
//             Generated by version version GALGAS_BETA_VERSION              *
//                       may 13th, 2011, at 16h40'45"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "sara_cli_options.h"

//---------------------------------------------------------------------------*
//                                                                           *
//                               Bool options                                *
//                                                                           *
//---------------------------------------------------------------------------*

C_BoolCommandLineOption gOption_sara_5F_cli_5F_options_displayBDDvalues ("sara_cli_options",
                                         "displayBDDvalues",
                                         118,
                                         "display-bdd-values",
                                         "displays values for every BDD") ;

C_BoolCommandLineOption gOption_sara_5F_cli_5F_options_displayBDDvaluesCount ("sara_cli_options",
                                         "displayBDDvaluesCount",
                                         99,
                                         "display-bdd-values-count",
                                         "displays values count for every BDD") ;

//---------------------------------------------------------------------------*
//                                                                           *
//                               UInt options                                *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*
//                                                                           *
//                              String options                               *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2



