//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'sara_scanner.h'                            *
//         Generated by version GALGAS_BETA_VERSION (LL(1) grammar)          *
//                     january 22th, 2007, at 22h16'43"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef sara_scanner_0_DEFINED
#define sara_scanner_0_DEFINED

//---------------------------------------------------------------------------*

#include "galgas/GGS_lstring.h"
#include "galgas/GGS_luint.h"
#include "galgas/GGS_lsint.h"
#include "galgas/GGS_luint64.h"
#include "galgas/GGS_lsint64.h"
#include "galgas/GGS_lchar.h"
#include "galgas/GGS_ldouble.h"
#include "galgas/GGS_lbool.h"

//---------------------------------------------------------------------------*

#include "galgas/C_Lexique.h"

//---------------------------------------------------------------------------*
//                                                                           *
//                          Lexical scanner class                            *
//                                                                           *
//---------------------------------------------------------------------------*

class cTokenFor_sara_scanner : public cToken {
  public : C_String identifierString ; // user defined attribute
  public : uint32 ulongValue ; // user defined attribute
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Lexical scanner class                            *
//                                                                           *
//---------------------------------------------------------------------------*

class sara_scanner : public C_Lexique {
//--- Declaring a protected virual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~sara_scanner (void) {}
  #endif

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

//--- Terminal symbols enumeration
  public : enum {sara_scanner_1_,
  sara_scanner_1_identifier,
  sara_scanner_1_auto,
  sara_scanner_1_state,
  sara_scanner_1_first,
  sara_scanner_1_last,
  sara_scanner_1_goto,
  sara_scanner_1_timer,
  sara_scanner_1_true,
  sara_scanner_1_false,
  sara_scanner_1_nofirst,
  sara_scanner_1_nolast,
  sara_scanner_1_modalcompadd,
  sara_scanner_1_exclude,
  sara_scanner_1_modalcompsub,
  sara_scanner_1_include,
  sara_scanner_1_to,
  sara_scanner_1_scenario,
  sara_scanner_1_trans,
  sara_scanner_1_ite_5Fcache,
  sara_scanner_1_and_5Fcache,
  sara_scanner_1_map,
  sara_scanner_1_bdd,
  sara_scanner_1_bool,
  sara_scanner_1_use_5Fand,
  sara_scanner_1_use_5Fite,
  sara_scanner_1_use_5Fand_5Fite,
  sara_scanner_1_check,
  sara_scanner_1_checkbool,
  sara_scanner_1_checkidentical,
  sara_scanner_1__2C,
  sara_scanner_1__3B,
  sara_scanner_1__3A,
  sara_scanner_1__7B,
  sara_scanner_1__7D,
  sara_scanner_1__2D_3E,
  sara_scanner_1__26,
  sara_scanner_1__7E,
  sara_scanner_1__3F,
  sara_scanner_1__21,
  sara_scanner_1__7C,
  sara_scanner_1__7C_7C,
  sara_scanner_1__2B,
  sara_scanner_1__28,
  sara_scanner_1__29,
  sara_scanner_1__3A_3D,
  sara_scanner_1__5E,
  sara_scanner_1__3D,
  sara_scanner_1__2A,
  sara_scanner_1__40,
  sara_scanner_1__2A_2A,
  sara_scanner_1_literal_5Fstring,
  sara_scanner_1_machineIdf,
  sara_scanner_1_literal_5Finteger} ;

//--- Key words table 'delimitorsList'
  public : static const sint16 sara_scanner_table_size_delimitorsList ;
  private : static const C_lexique_table_entry sara_scanner_table_for_delimitorsList [21] ;
  public : static sint16 search_into_delimitorsList (const C_String & inSearchedString) ;

//--- Key words table 'keyWordList'
  public : static const sint16 sara_scanner_table_size_keyWordList ;
  private : static const C_lexique_table_entry sara_scanner_table_for_keyWordList [28] ;
  public : static sint16 search_into_keyWordList (const C_String & inSearchedString) ;

  protected : virtual bool parseLexicalToken (void) ;
  protected : virtual sint16 parseLexicalTokenForLexicalColoring (void) ;
  protected : virtual void appendTerminalMessageToSyntaxErrorMessage (const sint16 numeroTerminal,
                                                              C_String & messageErreur) ;

//--- Constructor
  public : sara_scanner (AC_galgas_io * inGalgasInputOutput COMMA_LOCATION_ARGS) ;
//--- Get attribute values
  public : void _assignFromAttribute_identifierString (GGS_lstring & outValue) const ;
  public : void _assignFromAttribute_ulongValue (GGS_luint & outValue) const ;
//--- Get terminal count
  public : virtual sint16 terminalVocabularyCount (void) const { return 53 ; }
//--- Get Token String
  public : virtual C_String getCurrentTokenString (const cToken * inTokenPtr) const ;
//--- Enter Token
  protected : void _enterToken (const cTokenFor_sara_scanner & inToken) ;
//--- Style Definition
  public : static sint32 getStylesCount (void) ;
  public : static const char * getStyleName (const sint32 inIndex) ;
  public : static const char * getStyleIdentifier (const sint32 inIndex) ;
//--- Virtual method called getting terminal style index
  public : virtual uint8 terminalStyleIndex (const sint32 inTerminal) ;
} ;

//---------------------------------------------------------------------------*

#endif
