//---------------------------------------------------------------------------*
//                                                                           *
//                          File 'sara_scanner.h'                            *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     november 1st, 2010, at 15h57'3"                       *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1


#ifndef sara_5F_scanner_0_DEFINED
#define sara_5F_scanner_0_DEFINED

//---------------------------------------------------------------------------*

#include "galgas/GGS_lstring.h"
#include "galgas/GGS_luint.h"
#include "galgas/GGS_lsint.h"
#include "galgas/GGS_luint64.h"
#include "galgas/GGS_lsint64.h"
#include "galgas/GGS_lchar.h"
#include "galgas/GGS_ldouble.h"
#include "galgas/GGS_lbool.h"
#include "galgas2/C_Lexique.h"

//---------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------*
//                                                                           *
//                    E X T E R N    R O U T I N E S                         *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*
//                                                                           *
//                    E X T E R N    F U N C T I O N S                       *
//                                                                           *
//---------------------------------------------------------------------------*

//---------------------------------------------------------------------------*
//                                                                           *
//                       T O K E N    C L A S S                              *
//                                                                           *
//---------------------------------------------------------------------------*

class cTokenFor_sara_5F_scanner : public cToken {
  public : C_String mLexicalAttribute_identifierString ;
  public : PMUInt32 mLexicalAttribute_ulongValue ;

  public : cTokenFor_sara_5F_scanner (void) ;
} ;

//---------------------------------------------------------------------------*
//                                                                           *
//                     S C A N N E R    C L A S S                            *
//                                                                           *
//---------------------------------------------------------------------------*

class C_Lexique_sara_5F_scanner : public C_Lexique {
//--- Constructors
  public : C_Lexique_sara_5F_scanner (C_Compiler * inCallerCompiler,
                       const C_String & inDependencyFileExtension,
                       const C_String & inDependencyFilePath,
                       C_galgas_io * inParametersPtr,
                       const C_String & inSourceFileName
                       COMMA_LOCATION_ARGS) ;

  public : C_Lexique_sara_5F_scanner (C_Compiler * inCallerCompiler,
                       C_galgas_io * inParametersPtr,
                       const C_String & inSourceString,
                       const C_String & inStringForError
                       COMMA_LOCATION_ARGS) ;

//--- Declaring a protected virtual destructor enables the compiler to raise
//    an error if a direct delete is performed; only the static method
//    C_GGS_Object::detachPointer may invoke delete.
  #ifndef DO_NOT_GENERATE_CHECKINGS
    protected : virtual ~ C_Lexique_sara_5F_scanner (void) {}
  #endif


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


//--- Terminal symbols enumeration
  public : enum {kToken_,
   kToken_identifier,
   kToken_literal_5F_string,
   kToken_machineIdf,
   kToken_literal_5F_integer,
   kToken_comment,
   kToken_auto,
   kToken_state,
   kToken_first,
   kToken_last,
   kToken_goto,
   kToken_true,
   kToken_false,
   kToken_nofirst,
   kToken_nolast,
   kToken_modalcompadd,
   kToken_exclude,
   kToken_modalcompsub,
   kToken_include,
   kToken_to,
   kToken_scenario,
   kToken_trans,
   kToken_display,
   kToken_ite_5F_cache,
   kToken_and_5F_cache,
   kToken_map,
   kToken_bdd,
   kToken_bool,
   kToken_use_5F_and,
   kToken_use_5F_ite,
   kToken_use_5F_and_5F_ite,
   kToken_check,
   kToken_checkbool,
   kToken_checkidentical,
   kToken__2C_,
   kToken__3B_,
   kToken__3A_,
   kToken__7B_,
   kToken__7D_,
   kToken__2D__3E_,
   kToken__26_,
   kToken__7E_,
   kToken__3F_,
   kToken__21_,
   kToken__7C_,
   kToken__7C__7C_,
   kToken__2B_,
   kToken__28_,
   kToken__29_,
   kToken__3A__3D_,
   kToken__5E_,
   kToken__3D_,
   kToken__2A_,
   kToken__40_,
   kToken__2A__2A_} ;

//--- Key words table 'keyWordList'
  public : static PMSInt16 search_into_keyWordList (const C_String & inSearchedString) ;

//--- Key words table 'delimitorsList'
  public : static PMSInt16 search_into_delimitorsList (const C_String & inSearchedString) ;
  

//--- Assign from attribute (v1)
  public : void assignFromAttribute_identifierString (GGS_lstring & outValue) const ;
  public : void assignFromAttribute_ulongValue (GGS_luint & outValue) const ;


//--- Assign from attribute (v2)
  public : GALGAS_lstring synthetizedAttribute_identifierString (void) const ;
  public : GALGAS_luint synthetizedAttribute_ulongValue (void) const ;


//--- Attribute access
  public : C_String attributeValue_identifierString (void) const ;
  public : PMUInt32 attributeValue_ulongValue (void) const ;


//--- Parse lexical token
  protected : virtual bool parseLexicalToken (void) ;

//--- Append terminal message
  protected : virtual void appendTerminalMessageToSyntaxErrorMessage (const PMSInt16 numeroTerminal,
                                                              C_String & messageErreur) ;

//--- Get terminal count
  public : virtual PMSInt16 terminalVocabularyCount (void) const { return 54 ; }

//--- Get Token String
  public : virtual C_String getCurrentTokenString (const cToken * inTokenPtr) const ;

//--- Enter Token
  protected : void enterToken (const cTokenFor_sara_5F_scanner & inToken) ;
} ;

//---------------------------------------------------------------------------*

#endif
