//---------------------------------------------------------------------------*
//                                                                           *
//               File 'separateHeaderFor_C_5F_orExpression.h'                *
//             Generated by version version GALGAS_BETA_VERSION              *
//                      april 26th, 2012, at 18h10'3"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                  Pointer class for @C_orExpression class                  *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_5F_orExpression : public cPtr_AC_5F_boolExpression {
//--- START OF USER ZONE 2

  public : virtual C_BDD computeBDD (C_Compiler * inCompiler,
                                     const TC_Array <C_saraMachine> & inSaraSystemArray,
                                     const PMUInt32 inVariablesCount,
                                     const PMUInt32 inBDDslotOffset) const ;

//--- END OF USER ZONE 2

//--- Attributes
  public : GALGAS_AC_5F_boolExpression mAttribute_mLeftExpression ;
  public : GALGAS_AC_5F_boolExpression mAttribute_mRightExpression ;

//--- Constructor
  public : cPtr_C_5F_orExpression (const GALGAS_AC_5F_boolExpression & in_mLeftExpression,
                                   const GALGAS_AC_5F_boolExpression & in_mRightExpression
                                   COMMA_LOCATION_ARGS) ;

//--- Attribute accessors
  public : VIRTUAL_IN_DEBUG GALGAS_AC_5F_boolExpression reader_mLeftExpression (UNUSED_LOCATION_ARGS) const ;
  public : VIRTUAL_IN_DEBUG GALGAS_AC_5F_boolExpression reader_mRightExpression (UNUSED_LOCATION_ARGS) const ;
//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

