//---------------------------------------------------------------------------*
//                                                                           *
//             File 'separateHeaderFor_C_5F_machineComponent.h'              *
//             Generated by version version GALGAS_BETA_VERSION              *
//                      july 16th, 2011, at 15h22'18"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                Pointer class for @C_machineComponent class                *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_5F_machineComponent : public cPtr_AC_5F_job {
//--- START OF USER ZONE 2

  public : virtual void compute (C_Compiler * inCompiler,
                                 TC_Array <C_saraMachine> & ioSaraSystemArray,
                                 const bool inDisplayBDDvaluesCount,
                                 const bool inDisplayBDDvalues) const ;

//--- END OF USER ZONE 2

//--- Attributes
  public : GALGAS_lstring mAttribute_mMachineName ;
  public : GALGAS_uint mAttribute_mMachineIndex ;
  public : GALGAS_uint mAttribute_mInputVariableCount ;
  public : GALGAS_uint mAttribute_mInputAndInternalVariableCount ;
  public : GALGAS_M_5F_variablesMap mAttribute_mVariablesMap ;
  public : GALGAS_AC_5F_machineDefinition mAttribute_mDefinition ;

//--- Constructor
  public : cPtr_C_5F_machineComponent (const GALGAS_lstring & in_mMachineName,
                                       const GALGAS_uint & in_mMachineIndex,
                                       const GALGAS_uint & in_mInputVariableCount,
                                       const GALGAS_uint & in_mInputAndInternalVariableCount,
                                       const GALGAS_M_5F_variablesMap & in_mVariablesMap,
                                       const GALGAS_AC_5F_machineDefinition & in_mDefinition
                                       COMMA_LOCATION_ARGS) ;

//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

