//---------------------------------------------------------------------------*
//                                                                           *
//  File 'separateHeaderFor_C_5F_substractiveModalCompositionComponent.h'    *
//                 Generated by version GALGAS_BETA_VERSION                  *
//                     october 30th, 2010, at 11h32'46"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//     Pointer class for @C_substractiveModalCompositionComponent class      *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_5F_substractiveModalCompositionComponent : public cPtr_AC_5F_machineDefinition {

//--- START OF USER ZONE 2

  public : virtual void computeFromExpression (C_Compiler * inCompiler,
                                               const TC_Array <C_saraMachine> & inSaraSystemArray,
                                               const PMUInt16 inVariablesCount,
                                               C_BDD & outInitialStatesBDD,
                                               C_BDD & outTerminalStatesBDD,
                                               C_BDD & outAccessibilityRelationBDD) const ;

//--- END OF USER ZONE 2

//--- Attributes
  public : GALGAS_M_5F_modesMap mAttribute_mModeMap ;
  public : GALGAS_ListForModes mAttribute_mExclusionList ;

//--- Constructor
  public : cPtr_C_5F_substractiveModalCompositionComponent (const GALGAS_M_5F_modesMap & in_mModeMap,
                                                            const GALGAS_ListForModes & in_mExclusionList
                                                            COMMA_LOCATION_ARGS) ;
//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

