//-----------------------------------------------------------------------------*
//                                                                             *
//            File 'separateHeaderFor_C_5F_machineDisplayStates.h'             *
//                         Generated by version 2.5.8                          *
//                        may 19th, 2014, at 19h44'47"                         *
//                                                                             *
//-----------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//-----------------------------------------------------------------------------*
//                                                                             *
//              Pointer class for @C_machineDisplayStates class              *
//                                                                             *
//-----------------------------------------------------------------------------*

class cPtr_C_5F_machineDisplayStates : public cPtr_AC_5F_job {
//--- START OF USER ZONE 2

  public : virtual void compute (C_Compiler * inCompiler,
                                 TC_Array <C_saraMachine> & ioSaraSystemArray,
                                 const bool inDisplayBDDvaluesCount,
                                 const bool inDisplayBDDvalues) const ;

//--- END OF USER ZONE 2

//--- Attributes
  public : GALGAS_uint mAttribute_mMachineIndex ;

//--- Constructor
  public : cPtr_C_5F_machineDisplayStates (const GALGAS_uint & in_mMachineIndex
                                           COMMA_LOCATION_ARGS) ;

//--- Attribute accessors
  public : VIRTUAL_IN_DEBUG GALGAS_uint reader_mMachineIndex (UNUSED_LOCATION_ARGS) const ;
//--- Description
  public : virtual void description (C_String & ioString,
                                     const int32_t inIndentation) const ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

