//---------------------------------------------------------------------------*
//                                                                           *
//            File 'separateHeaderFor_C_5F_VariableExpression.h'             *
//             Generated by version version GALGAS_BETA_VERSION              *
//                      july 16th, 2011, at 15h22'18"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//               Pointer class for @C_VariableExpression class               *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_5F_VariableExpression : public cPtr_AC_5F_boolExpression {
//--- START OF USER ZONE 2

  public : virtual C_BDD computeBDD (C_Compiler * inCompiler,
                                     const TC_Array <C_saraMachine> & inSaraSystemArray,
                                     const PMUInt16 inVariablesCount,
                                     const PMUInt16 inBDDslotOffset) const ;

//--- END OF USER ZONE 2

//--- Attributes
  public : GALGAS_uint mAttribute_mInputVarIndex ;

//--- Constructor
  public : cPtr_C_5F_VariableExpression (const GALGAS_uint & in_mInputVarIndex
                                         COMMA_LOCATION_ARGS) ;

//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

