//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                  File 'separateHeaderFor_AC_5F_boolExpression.h'                                    *
//                                             Generated by version 2.7.0                                              *
//                                            august 8th, 2014, at 20h4'0"                                             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1

#include "bdd/C_BDD.h"

#ifndef C_saraMachine_DEFINED
  #define C_saraMachine_DEFINED
  class C_saraMachine {
    public : C_saraMachine (void) ;
    public : C_String mMachineName ;
    public : uint32_t mInputVariablesCount ;
    public : uint32_t mInputAndInternalVariablesCount ;
    public : TC_UniqueArray <C_String> mNamesArray ;
    public : C_BDD mInitialStatesBDD ;
    public : C_BDD mTerminalStatesBDD ;
    public : C_BDD mTransitionRelationBDD ;
    public : C_BDD mAccessibleStatesBDD ;
  } ;
#endif

//--- END OF USER ZONE 1

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                     Pointer class for @AC_boolExpression class                                      *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

class cPtr_AC_5F_boolExpression : public acPtr_class {
//--- START OF USER ZONE 2

  public : virtual C_BDD computeBDD (C_Compiler * inCompiler,
                                     const TC_Array <C_saraMachine> & inSaraSystemArray,
                                     const uint32_t inVariablesCount,
                                     const uint32_t inBDDslotOffset) const = 0 ;

//--- END OF USER ZONE 2

//--- Attributes

//--- Constructor
  public : cPtr_AC_5F_boolExpression (LOCATION_ARGS) ;

//--- Attribute accessors
//--- Description
  public : virtual void description (C_String & ioString,
                                     const int32_t inIndentation) const = 0 ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const = 0 ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const = 0 ;

} ;

