//---------------------------------------------------------------------------*
//                                                                           *
//              File 'separateHeaderFor_C_5F_importMachine.h'                *
//             Generated by version version GALGAS_BETA_VERSION              *
//                      july 16th, 2011, at 15h22'18"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------*
//                                                                           *
//                 Pointer class for @C_importMachine class                  *
//                                                                           *
//---------------------------------------------------------------------------*

class cPtr_C_5F_importMachine : public cPtr_AC_5F_machineDefinition {
//--- START OF USER ZONE 2

  public : virtual void computeFromExpression (C_Compiler * inCompiler,
                                               const TC_Array <C_saraMachine> & inSaraSystemArray,
                                               const PMUInt16 inVariablesCount,
                                               C_BDD & outInitialStatesBDD,
                                               C_BDD & outTerminalStatesBDD,
                                               C_BDD & outAccessibilityRelationBDD) const ;

//--- END OF USER ZONE 2

//--- Attributes
  public : GALGAS_uint mAttribute_mIndexOfImportedMachine ;
  public : GALGAS_L_5F_translationVector mAttribute_mTranslationVector ;

//--- Constructor
  public : cPtr_C_5F_importMachine (const GALGAS_uint & in_mIndexOfImportedMachine,
                                    const GALGAS_L_5F_translationVector & in_mTranslationVector
                                    COMMA_LOCATION_ARGS) ;

//--- Description
  public : virtual void description (C_String & ioString,
                                     const PMSInt32 inIndentation) const ;

  public : virtual typeComparisonResult dynamicObjectCompare (const acPtr_class * inOperandPtr) const ;

  public : virtual const C_galgas_type_descriptor * classDescriptor (void) const ;

} ;

